config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "doctors", to: 'doctors#index'
  #added destroy routes
  resources :searches, only: %i[index create destroy]
  resources :specialties, only: %i[index]
  get "my_searches", to: "dashboards#my_searches"
  get "my_appointments", to: "dashboards#my_appointments"
  get "appointment_show", to: "dashboards#appointment_show"
  delete "my_appointments/:id", to: "dashboards#my_appointments_destroy", as: 'my_appointment'
  resources :notifications, only: [:show, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :user, optional: true
  has_many :notifications, dependent: :destroy
  after_create :create_notifications

  private

  def create_notifications
    user = User.joins(:searches)
               .where(searches: {specialty: self.doctor.specialties})
               .order("searches.created_at DESC").first
    if user
      Notification.create!(appointment: self, user: user)
    end
  end

end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :doctor_specialties
  has_many :specialties, through: :doctor_specialties
  has_many :appointments
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  accepts_nested_attributes_for :specialties
end

app/models/doctor_specialty.rb
class DoctorSpecialty < ApplicationRecord
  belongs_to :specialty
  belongs_to :doctor
end

app/models/notification.rb
class Notification < ApplicationRecord
  include ActionView::Helpers
  belongs_to :user
  belongs_to :appointment

  after_create_commit :send_notification

  def send_notification
    host = Rails.env.development? ? "http://localhost:3000" : "http://www.instantdoc.me"
    url = Rails.application.routes.url_helpers.notification_url(self, host: host)

    text = "Dr. #{appointment.doctor.last_name} is available in #{distance_of_time_in_words_to_now(appointment.start_at)}.\n"
    text += "Go to #{url} to confirm."
    TwilioClient.new.send_message(text, self.user)


  end
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :user
  belongs_to :specialty
  validates :location, :radius, presence: true
end

app/models/specialty.rb
class Specialty < ApplicationRecord
  has_many :doctor_specialties
  has_many :doctors, through: :doctor_specialties
  has_many :searches
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :searches
  has_many :appointments
  has_many :notifications
  has_many :doctors, through: :appointments
  validates :telephone, format: { with: /\(?\+\(?49\)?[ ()]?([- ()]?\d[- ()]?){10}/,
  message: 'Please give a german phone number' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  include Pundit
  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :telephone])

    # For additional in app/views/devise/registrations/edit.html.erb
  end

  private
  def set_specialties
    @specialties = Specialty.all
    @specialties = @specialties.order(name: :ASC)
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  skip_after_action :verify_authorized
  before_action :set_specialties, only: %i[my_searches my_appointments]

  def my_searches
    # creating instance variable doctors_navbar for if else in application erb file
    @dashboard_navbar = true
    @footer = true
    @dashboard = Search.where("user_id == #{current_user.id}")

    # @dashboarda = @dashboard.searches.where(user.id == current_user)
    # current_user
  end

  def my_appointments
    # creating instance variable doctors_navbar for if else in application erb file
    @dashboard_navbar = true
    @footer = true
    @dashboard_a = Appointment.where("user_id == #{current_user.id}")
  end

  def my_appointments_destroy
    appointment = Appointment.find(params[:id])
    authorize(appointment)
    appointment.destroy
    redirect_to my_appointments_path
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_specialties, only: :index
  skip_before_action :authenticate_user!, only: %i[index]


  def index
    @doctors_navbar = true
    if params[:specialties].present? && params[:location].present? # We check if the user gave as a specitly
      radius = params[:radius].empty? ? 5 : params[:radius].to_i
      @doctors = policy_scope(Doctor.geocoded.near(params[:location], radius).joins(:specialties).where({ specialties: { id: params[:specialties].to_i } })) # We search for a doctor with this specialty
      @search = Search.new
    else
      @doctors = Doctor.geocoded
    end
    @markers = @doctors.map do |doctor|
      {
        lat: doctor.latitude,
        lng: doctor.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { doctor: doctor })
      }
    end
  end

    private

    def search_params
      params.require(:doctor).permit(:specialty, :location)
    end
  end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def show
    @dashboard_navbar = true
    @notification = Notification.find(params[:id])
    authorize(@notification)
    @current_time = Date.today
  end

  def update
    @notification = Notification.find(params[:id])
    authorize(@notification)
    @appointment = @notification.appointment
    @appointment.update(notification_params)

    if @appointment.status == "confirmed"
      @appointment.update(user: current_user)
      redirect_to my_appointments_path
    else
      current_user.searches.where(specialty: @appointment.doctor.specialties).destroy_all
      # redirect to appointments#show
    end
  end

  private

  def notification_params
    params.require(:notification).permit(:status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_specialties, only: [:home]
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @home = true
    @footer = true
    @doctor
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: [ :destroy ]

  def index
    @searches = Search.all
    authorize @searches
  end

  def create
    @search = Search.new(search_params)
    @search.user = current_user
    authorize @search

    if @search.save
      redirect_to my_searches_path
    else
      render "doctors/index"
    end
  end

  def destroy
    @search.destroy
    authorize @search
    redirect_to my_searches_path
  end

  private

  def search_params
    params[:search].permit(:location, :radius, :specialty_id)
  end

  def set_search
    @search = Search.find(params[:id])
  end

end

app/controllers/specialties_controller.rb
class SpecialtiesController < ApplicationController
  def index

    @doctors = Doctor.all
  end

  private

  def search_params
    params.require(:doctor).permit(:specialty, :location)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/dashboards/my_appointments.html.erb
<div class="container" id="appointment">
  <nav>
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
      <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Upcoming</a>
      <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">History</a>
    </div>
  </nav>
  <div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
      <div id="doctor-list">
        <% current_user.appointments.order(start_at: :ASC).each do |appointment| %>
          <div class="card-doc">
            <div class="header-card">
              <i class="far fa-calendar"></i> <%= appointment.start_at.strftime("%A, %B %-d") %>
              <i class="far fa-clock"></i> <%= appointment.start_at.strftime("%H:%M") %>
            </div>
            <div class="flex-card">
              <img id="doc-image"src=<%=appointment.doctor.picture_url%> alt="A doctor">
              <div class="card-doc-info">
                <h3><%= appointment.doctor.first_name %> <%= appointment.doctor.last_name %></h3>

                <% appointment.doctor.specialties.each do |specialty| %>
                  <p><%= specialty.name %></p>
                <% end %>
                <p><i class="far fa-calendar-check"></i> <strong class="<%= appointment.status%>-color"> <%= appointment.status %></strong> </p>
                <p><i class="fas fa-map-marker-alt"></i> <%= appointment.doctor.address %></strong></p>
              </div>
            </div>
            <div class="button-del">
              <a href="#" class="btn btn-del" data-toggle="modal" data-target="#delModalCenter">Cancel</a>
            </div>
          </div>
                <!-- modal -->
      <div class="modal fade" id="delModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLongTitle">You're about to delete your booking</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <p>Are you sure?</p>
            </div>
            <div class="modal-footer">
              <%= link_to "Yes", my_appointment_path(appointment),class: "px-4 mr-5 btn btn-danger btn-lg" ,method: :delete%>
              <p><button type="button" class="px-3 btn btn-secondary btn-lg" data-dismiss="modal">Close</button></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
        </div>
      </div>
      <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
      ...
      </div>
  </div>
  </div>

<%= render 'shared/map' %>

app/views/dashboards/my_searches.html.erb
<!-- <h2 class="blue-bar" id="welcome-bar">My searches</h2> -->
<p class="idx-instruction"><i class="fas fa-info-circle"></i> You will get notified by SMS as soon as your doctor is available</p>
<div class="container-search" id="search notif-show">

  <h2 style="font-size: 34px;  font-weight: bold; color: #006565; padding-top: 5px">My Queues</h2>

  <% current_user.searches.each do |search| %>
    <div class="card-doc" id="search">
      <!-- <div class="flex-card" id="flex-search"> -->
        <div class="card-doc-info p-0">
          <h4><%= search.specialty.name %> near <%= search.location %></h4>
          <p><i class="fas fa-map-marked-alt"></i> Within <%= search.radius != 0 ? search.radius : "5" %> km</p>
        </div>
        <div class="text-right">
          <%= link_to "Cancel", search_path(search), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-del" %>
        </div>
      <!-- </div> -->
    </div>
  <% end %>
</div>

app/views/doctors/_info_window.html.erb
<h3><%= doctor.first_name %> <%= doctor.last_name %></h3>
<h5> <%= (Specialty.find params[:specialties].to_i).name %></h5>

app/views/doctors/index.html.erb
<div id='map-cont' class="container">
  <div id='doctor-list'>
    <p class="idx-instruction"><i class="fas fa-info-circle"></i> Tap 'notify me' to get notified on any next available appointment with <%=  Specialty.find(params[:specialties]).name %>s in <%= params[:location] %></p>
    <% @doctors.each do |doctor| %>
      <div class="card-doc">
        <img id="doc-image"src=<%=doctor.picture_url%> alt="A doctor">
        <div class="card-doc-info">
          <h3> <%= doctor.first_name %> <%= doctor.last_name %></h3>
          <% doctor.specialties.each do |specialty| %>
            <% if specialty.id == params[:specialties].to_i %>
              <p class="card-doc-info-specialty"> <%= specialty.name %></p>
            <% end %>
          <% end %>
          <p><i class="fas fa-map-marker-alt"></i> <%= doctor.address %></p>
          <p><i class="fas fa-hourglass-half"></i><span> <%= doctor.waiting_time %></span> hr</p>
        </div>
        <div class="">
          <i class="fas fa-link ext-link"></i>
        </div>
      </div>
    <% end %>

    <%= form_for @search do |f| %>
      <%= f.hidden_field :specialty_id, { :value => params[:specialties] } %>
      <%= f.hidden_field :location, { :value => params[:location] } %>
      <%= f.hidden_field :radius, { :value => params[:radius] } %>
      <%= f.submit "Notify Me", :class => 'btn-ter' %>
    <% end %>
  </div>
  <%= render 'shared/map' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <%= favicon_link_tag 'favicon.ico' %>
    <link href="https://fonts.googleapis.com/css?family=Khula|Noto+Sans|Noto+Sans+KR|Roboto|Roboto+Condensed|Spartan&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Bebas+Neue|Pacifico&display=swap" rel="stylesheet">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <% if @home %>
      <%= render 'pages/homepage_navbar' %>
    <% elsif @doctors_navbar %>
      <%= render 'shared/navbar'  %>
    <% elsif @dashboard_navbar  %>
      <%= render 'shared/general_navbar' %>
    <% end %>
    <%= yield %>
    <% if @footer  %>
      <%= render 'shared/footer' %>
    <% end  %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/notifications/show.html.erb
<div class="container" id="notif-show">
  <div class="appointment-pop">
    <h4 id="pop-title">We've got you an available slot!</h4>
    <div class="pop-schedule">
      <i class="far fa-calendar"></i> <%= @notification.appointment.start_at.strftime("%A, %B %-d ") %>
      <br>
      <i class="far fa-clock"></i> <%= @notification.appointment.start_at.strftime("%H:%M") %>
    </div>
  </div>
  <div class="doc-pop">
    <h4 id="ter-title">Your doctor:</h4>
    <div class="card-doc" id="notif-doc-card">
      <img id="doc-image"src=<%= @notification.appointment.doctor.picture_url%> alt="A doctor">
      <div class="card-doc-info">
        <p id="notif-doc-info">Dr <%= @notification.appointment.doctor.first_name %> <%= @notification.appointment.doctor.last_name %></p>
        <p id="notif-doc-info"><%= @notification.appointment.doctor.address%> </p>
      </div>
    </div>
  </div>
  <div class="confirm-pop">
    <h4 id="ter-title">Will you book this appointment?</h4>
    <h1 id="notif-timer" data-notificationtime="<%= @notification %>"></h1>
    <div class="confirm-buttons">
      <%= button_to "Confirm", notification_path(@notification),
                               method: :patch,
                               params: { notification: { status: "confirmed" }},
                               :class => 'btn-yellow' %>

      <%= button_to "Decline", notification_path(@notification),
                               method: :patch,
                               params: { notification: { status: "declined" }},
                               :class => 'cancel-green mt-3' %>
    </div>
  </div>
</div>

<!-- javascript code for timer, refactor later -->

<%= content_for(:after_js) do  %>
<script>

  const notifTimer = document.getElementById("notif-timer");
  // const countdown = notifTime.dataset.notificationTime

  if (notifTimer) {
    var s = Number("<%= @notification.created_at.to_i * 1000 %>");

    var countDownDate = new Date(s).getTime();
    var coundDownPlus5 = new Date(s + (5*60000)).getTime() ;
    console.log(coundDownPlus5);

    // Update the count down every 1 second
    var x = setInterval(function() {

      // Get today's date and time
      var now = new Date().getTime();
      // console.log(now);
      // Find the distance between now and the count down date
      var timeDiff = coundDownPlus5 - now;
      // console.log(coundDownPlus5);
      // console.log(timeDiff);
      // If the count down is over, write some text
      if (timeDiff < 0) {
        clearInterval(x);
        notifTimer.innerHTML = "EXPIRED";
        return;
      }
      // otherwise, calculate the minutes and seconds left
      // Time calculations for days, hours, minutes and seconds
      var minutes = Math.floor((timeDiff % (1000 * 60 * 60)) / (1000 * 60));
      var seconds = Math.floor((timeDiff % (1000 * 60)) / 1000);

      // Output the result in timer element
      notifTimer.innerHTML = minutes + "m " + seconds + "s ";
    }, 1000);

  }

</script>
<% end %>

app/views/pages/_homepage_navbar.html.erb
<div class="nav-container">
  <div id="mySidenav" class="sidenav navbar-expand navbar-light navbar-lewagon navbar-fixed-top">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
      <% if user_signed_in? %>
        <div>
           <p class="welcome-user">Hi, <%= current_user.first_name.capitalize %>!</p>
        </div>
        <%= link_to "Home", root_path, class: "dropdown-item" %>
        <%= link_to "Edit my profile", edit_user_registration_path, class: "dropdown-item" %>
        <%= link_to "My queues", my_searches_path, class: "dropdown-item" %>
        <%= link_to "My appointments", my_appointments_path, class: "dropdown-item" %>
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
      <% else %>
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
      <% end %>
  </div>

  <div class="nav-icon">
    <span style="font-size:30px;cursor:pointer" onclick="openNav()"> <%= image_tag "menu-white.png", class: "avatar dropdown-toggle", id: "navbarDropdown" %></span>
  </div>

</div>

<script>
function openNav() {
  document.getElementById("mySidenav").style.width = "250px";
}

function closeNav() {
  document.getElementById("mySidenav").style.width = "0";
}
</script>
<!--
<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
    <% if user_signed_in? %>
      <li class="nav-item dropdown" id="landing-page">
        <%= image_tag "menu-white.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <div>
             <p class="welcome-user">Hi, <%= current_user.first_name.capitalize %>!</p>
          </div>
          <%= link_to "Home", root_path, class: "dropdown-item" %>
          <%= link_to "Edit my profile", edit_user_registration_path, class: "dropdown-item" %>
          <%= link_to "My queues", my_searches_path, class: "dropdown-item" %>
          <%= link_to "My appointments", my_appointments_path, class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
    <% else %>
      <li class="nav-item dropdown" id="landing-page">
        <%= image_tag "menu-white.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </div>
    <% end %>
  </ul>
</div>
 -->

app/views/pages/home.html.erb
<div class="banner">
  <div class="container">
    <div class="landing-search">
      <div class="flex-search">
        <div class="title-wrapper">
          <h1 class="title">Get your doctor's appointment today</h1>
        </div>
        <%= form_tag doctors_path, method: :get, class: "search-form-control", id: "home-form" do %>
            <%= select_tag "specialties", options_from_collection_for_select(
            @specialties.all,
            :id, :name),
            class: 'form-control select2', id: "homepage", include_blank: true, required: true %>
            <%= text_field_tag :location,
              params[:location], as: :string,
              placeholder: 'Enter your address',
              id: 'address-input',
              required: true %>
            <%= label_tag "radius", "Travel distance" %>
            <%= select_tag "radius", options_from_collection_for_select([[2, "2 km"], [5, "5 km"], [10, "10 km"], [25, "25 km"], [50, "50 km"]], :first, :last) %>
            <%#= range_field_tag(:radius, 0, max: 150, step: 5, class: 'form-control') %>
            <%= submit_tag "Get your appointment!", class: "btn-green mt-3" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <%= image_tag "logo.png", alt: "logo", width: "25px" %>
    <p>InstantDoc</p>
    <!-- <i class="far fa-copyright"></i> -->
    <i class="fas fa-heart"></i>
  </div>
</div>

app/views/shared/_general_navbar.html.erb
<div class="nav-gen-container">
  <div id="mySidenav" class="sidenav navbar-expand navbar-light navbar-lewagon navbar-fixed-top">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
      <% if user_signed_in? %>
        <div>
           <p class="welcome-user">Hi, <%= current_user.first_name.capitalize %>!</p>
        </div>
        <%= link_to "Home", root_path, class: "dropdown-item" %>
        <%= link_to "Edit my profile", edit_user_registration_path, class: "dropdown-item" %>
        <%= link_to "My queues", my_searches_path, class: "dropdown-item" %>
        <%= link_to "My appointments", my_appointments_path, class: "dropdown-item" %>
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
      <% else %>
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
      <% end %>
  </div>

  <div class="nav-icon">
    <span style="font-size:30px;cursor:pointer" onclick="openNav()"> <%= image_tag "menu-white.png", class: "avatar dropdown-toggle", id: "navbarDropdown" %></span>
  </div>

</div>

<script>
function openNav() {
  document.getElementById("mySidenav").style.width = "250px";
}

function closeNav() {
  document.getElementById("mySidenav").style.width = "0";
}
</script>

<!-- <div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
    <% if user_signed_in? %>
      <li class="nav-item dropdown" id="general-page">
        <%= image_tag "menu-white.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdown">
          <div>
             <p class="welcome-user">Hi, <%= current_user.first_name.capitalize %>!</p>
          </div>
          <%= link_to "Home", root_path, class: "dropdown-item" %>
          <%= link_to "Edit my profile", edit_user_registration_path, class: "dropdown-item" %>
          <%= link_to "My queues", my_searches_path, class: "dropdown-item" %>
          <%= link_to "My appointments", my_appointments_path, class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
    <% else %>
      <li class="nav-item dropdown" id="general-page">
        <%= image_tag "menu-white.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdown">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </div>
    <% end %>
  </ul>
</div>
 -->

app/views/shared/_map.html.erb
<div
  id="map"
  style="height: 90vh; width: 100%; visibility: hidden;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>